---
title: "Stat 508 - Final Project"
output:
  pdf_document: default
  html_notebook: default
  
Author: "Adam Behrendorff, Nicholas Napier, Saqib Ali"
---


# Introduction
In this in project we are looking at the Jobs Data set for Classification

```{r}
library(caret)
library(text2vec)
library(tm)
library(dplyr)
library(data.table)
library("pls")
```


# Data
```{r}

JobsData <- read.csv("JobsData.csv", stringsAsFactors=FALSE, header = TRUE)
saveRDS(JobsData, file="JobsData.Rds")
JobsData <- readRDS("JobsData.Rds")

```


```{r}
JobsData$id <- seq.int(1:nrow(JobsData))

```

```{r}
train <- createDataPartition(JobsData$JobType, p = .01, list=FALSE)
jobsdata.training.subset <- JobsData[train,]
jobsdata.testing.subset <- JobsData[-train,]
```



```{r}
prep_fun = tolower
tok_fun = word_tokenizer

it_train = itoken(jobsdata.training.subset$JobDescription, 
             preprocessor = prep_fun, 
             tokenizer = tok_fun, 
             ids = jobsdata.training.subset$id, 
             progressbar = FALSE)


```

```{r}

stop_words = read.csv("stopwords.csv", header = FALSE, stringsAsFactors=FALSE)
stop_words <- as.character(stop_words$V1)
train_tokens = jobsdata.training.subset$JobDescription %>% prep_fun %>% tok_fun
it_train = itoken(train_tokens, 
                  ids = jobsdata.training.subset$id,
                  # turn off progressbar because it won't look nice in rmd
                  progressbar = FALSE)

vocab = create_vocabulary(it_train, stopwords = stop_words)

```


```{r}
pruned_vocab = prune_vocabulary(vocab, 
                                 term_count_min = 10, 
                                 doc_proportion_max = 0.25,
                                 doc_proportion_min = 0.001)
#pruned_vocab
vectorizer = vocab_vectorizer(pruned_vocab)

dtm_train = create_dtm(it_train, vectorizer)
dtm_train <- as.matrix(dtm_train)
dtm_train <- as.data.table(dtm_train)
dim(dtm_train)

```



```{r}
dim(dtm_train)
dim(jobsdata.training.subset)
```




```{r}
dtm_train$JobTypeReponse <- ifelse(jobsdata.training.subset$JobType=="Data Science", 1, 0)

```


```{r}
#set.seed(1)
#pcr.fit = pcr(JobTypeReponse ~., data=dtm_train, scale=TRUE, validation="CV") 
#validationplot(pcr.fit, val.type="MSEP")
```


```{r}
fit <- glm(dtm_train$JobTypeReponse~., data=dtm_train, family=binomial())
```


```{r}
it_test = jobsdata.testing.subset$JobDescription %>% 
  prep_fun %>% tok_fun %>% 
  # turn off progressbar because it won't look nice in rmd
  itoken(ids = jobsdata.testing.subset$id, progressbar = FALSE)
         

dtm_test = create_dtm(it_test, vectorizer)
dtm_test <- as.matrix(dtm_test)
dtm_test <- as.data.frame(dtm_test)
```


```{r}
pred <- predict(fit, dtm_test,  type = 'response')
pred <- ifelse(pred<0.5, "Non Data Science", "Data Science")
```


```{r}
mean(pred==jobsdata.testing.subset$JobType)
```

```{r}
table(pred,jobsdata.testing.subset$JobType)

```

# Analysis

# Conclusion
